{
    'name': 'AveriGo Opening Stock',
    'version': '16.0.1.0.0',
    'category': 'Sales',
    'author': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'summary': '',
    "description": """""",
    'depends': ['base', 'stock', 'base_averigo'],
    'data': [],
    'installable': True,
    'auto_install': False,
}
