{
    "name": "Averigo Equipment Management",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "Cybrosys Techno Solutions Pvt Ltd.",
    "website": "http://www.cybrosys.com",
    "category": "Accounting & Finance",
    "depends": ['account', 'base_averigo', 'micro_market',
                'averigo_accounting', 'averigo_sales_order',
                'averigo_security', 'web'],
    # "data": [
    #     'security/account_asset_security.xml',
    #     'security/ir.model.access.csv',
    #     'wizard/asset_journal_wizard.xml',
    #     'wizard/account_asset_compute.xml',
    #     'wizard/account_asset_remove.xml',
    #     'views/account_account.xml',
    #     'views/machine_view.xml',
    #     'views/account_asset.xml',
    #     'views/account_asset_group.xml',
    #     'views/account_asset_profile.xml',
    #     'views/account_move.xml',
    #     'views/account_move_line.xml',
    #     'views/account_asset_location.xml',
    #     'views/account_asset_transfer.xml',
    #     'views/account_asset_transfer_type.xml',
    #     'views/machine_parts_view.xml',
    #     'views/parts_purchase_view.xml',
    #     'views/menuitem.xml',
    #     'data/data.xml',
    #     'views/machine_template.xml',
    #     'views/res_partner.xml',
    #     'views/stock_warehouse.xml',
    #     'views/stock_warehouse_view.xml',
    #     'views/product_template.xml',
    #     'views/assets.xml',
    #
    # ],
    "excludes": ["account_asset"],
    "external_dependencies": {"python": ["python-dateutil"]},
}
