{
    'name': "Avreigo Periodic Sales Report",
    'version': '16.0.1.0.0',
    'author': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'summary': '',
    "description": """""",

    'depends': ['base', 'micro_market', 'product', 'stock', 'averigo_reports',
                'web', 'web_service', 'mail', 'base_averigo',
                'single_product_master'],

    # 'data': [
    #     # 'security/ir.model.access.csv',
    #     # 'security/security.xml',
    #     'views/action_manager.xml',
    #     'data/recurring_report.xml',
    #     'data/email_template.xml',
    #     'wizard/wizard.xml',
    #     'report/report.xml',
    #     'views/email_config_view.xml',
    #     'views/product_list_view.xml',
    #     # 'report/weekly_sales_template.xml',
    # ],
    'license': 'AGPL-3',
    'application': True,
    'installable': True,
    'auto_install': False,
}
