{
    "name": "Averigo Sales Order Updates",
    "summary": "Sales Order",
    "version": "16.0.1.0",
    "category": "",
    "website": "http://www.cybrosys.com",
    "description": """Averigo Sales Order""",
    "author": "Cybrosys Techno Solutions Pvt Ltd.",
    "license": "LGPL-3",
    "depends": ['averigo_sales_order', 'base', 'base_averigo',
                'sale_management', 'purchase', 'micro_market', 'calendar',
                'averigo_purchase',
                'micro_market', 'stock_dropshipping', 'delivery',
                'averigo_purchase', 'stock', 'stock_picking_batch',
                'averigo_accounting', 'averigo_picklist_updt',
                'averigo_portal_user'
                ],
    # "data": [
    #     'security/sale_order_user.xml',
    #     'views/sale_order_updt.xml',
    #     'views/picklist_updt.xml',
    #     'views/account_invoice.xml',
    #     'views/res_partner.xml',
    #     'views/portal_view_updt.xml',
    #     'views/packing_slip_update.xml',
    #     'views/invoice_signature.xml',
    # ],
    "installable": True,
}
