{
    "name": "Averigo Portal User",
    "summary": "Portal User",
    "version": "16.0.1.0",
    "category": "",
    "website": "http://www.cybrosys.com",
    "description": """Averigo Portal User""",
    "author": "Cybrosys Techno Solutions Pvt Ltd.",
    "license": "LGPL-3",
    "depends": [
        'base', 'base_averigo', 'sale_management', 'averigo_sales_order',
        'event', 'crm', 'calendar', 'mass_mailing', 'portal', 'mail',
        'auth_signup', 'digest', 'averigo_reports', 'averigo_crm',
    ],
    # "data": [
    #     'security/portal_group.xml',
    #     'security/ir.model.access.csv',
    #     'security/security.xml',
    #     'report/report.xml',
    #     'report/invoice_template.xml',
    #     'data/data.xml',
    #     'wizard/previous_order.xml',
    #     'views/email_template.xml',
    #     'views/portal_order.xml',
    #     'views/portal_reorder.xml',
    #     # 'views/portal_order_user.xml',
    #     'views/portal_order_form.xml',
    #     'views/averigo_portal.xml',
    #     'views/res_users.xml',
    #     'views/res_partner.xml',
    #     'views/notify_order.xml',
    #     'views/login_template.xml',
    #     'views/assets.xml',
    #     'views/portal_user_view.xml',
    # ],
    # 'qweb': [
    #     'static/src/xml/activity.xml',
    #     'static/src/xml/portal_support.xml',
    # ],
    "installable": True,
    "application": True,
}
