{
    'name': 'Overage Shrinkage Spoilage Report',
    'version': '16.0.1.0.0',
    'category': 'Reports',
    'author': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'summary': '',
    "description": """""",
    'depends': ['inventory_change_report'],
    'data': [],
    'installable': True,
    'auto_install': False,
}
