from . import zip_county
from . import customer_contract
from . import user_session_history
from . import res_users
from . import res_app_users
from . import customer_type
from . import hr_employee
from . import res_partner
from . import res_division
from . import res_company
from . import uom_uom
