{
    'name': 'AveriGo Purchase',
    'version': '16.0.1.0.0',
    'category': 'Sales',
    'author': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'summary': '',
    "description": """""",
    'depends': ['base', 'base_averigo', 'purchase', 'single_product_master', 'micro_market', 'averigo_employee_user'],
    # 'data': [
    #     'views/purchase_default.xml',
    #     'views/purchase_views.xml',
    #     'views/account_bill.xml',
    #     'views/res_vendors_views.xml',
    #     'views/account_view.xml',
    #     'views/hr_employee_view.xml',
    #     'views/product_views.xml',
    #     'views/stock_picking_views.xml',
    #     'views/res_users_view.xml',
    #     'views/purchase_order_template.xml',
    #     'views/purchase_quotation_template.xml',
    #     'data/data.xml',
    #     'security/ir.model.access.csv',
    #     'security/security.xml',
    #     'report/report.xml',
    #     'report/bill_template.xml',
    # ],
    'installable': True,
    'auto_install': False,
}


