from . import account_account
from . import account_asset
from . import account_asset_group
from . import account_asset_profile
from . import account_asset_line
from . import account_asset_recompute_trigger
# from . import account_fiscal_year
from . import account_move
from . import account_asset_location
from . import account_asset_transfer
from . import res_partner
from . import account_asset_loan
from . import stock_warehouse
from . import product_template
from . import purchase_order
from . import averigo_reordering_rule
from . import mail_activity
from . import machine_parts_line
from . import machine_placement
from . import notes
